# Generated by Django 4.2.2 on 2023-06-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_motos_modelos_remove_usuario_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='modelos',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='Producto',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='producto',
            name='agregar_carrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imgs/'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
