# Generated by Django 4.2.2 on 2023-06-27 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_motos_modelos_remove_usuario_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modelos',
            new_name='Motos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipo_usuario',
            new_name='nombre',
        ),
    ]
