# Generated by Django 4.2.3 on 2023-07-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_delete_modelos_remove_ventas_producto_and_more'),
        ('ventas', '0005_alter_producto_precio'),
    ]

    operations = [
    ]
